
/* Drop Tables */

DROP TABLE AUTH_MAPPING CASCADE CONSTRAINTS;
DROP TABLE CODING_COMMENT CASCADE CONSTRAINTS;
DROP TABLE CODING_FILE_GRP CASCADE CONSTRAINTS;
DROP TABLE CODING_LIKE CASCADE CONSTRAINTS;
DROP TABLE CODING_READCNT_HIST CASCADE CONSTRAINTS;
DROP TABLE CODING_BOARD CASCADE CONSTRAINTS;
DROP TABLE CODING_LOGIN_HIST CASCADE CONSTRAINTS;
DROP TABLE CODING_PW_HIST CASCADE CONSTRAINTS;
DROP TABLE CODING_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE CODING_AUTH_GRP CASCADE CONSTRAINTS;
DROP TABLE CODING_MENU CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE AUTH_MAPPING
(
	GRP_CD varchar2(10 char) NOT NULL,
	MENU_ID varchar2(200 char) NOT NULL,
	USE_YN varchar2(1 char) DEFAULT 'Y' NOT NULL,
	PRIMARY KEY (GRP_CD, MENU_ID)
);


CREATE TABLE CODING_AUTH_GRP
(
	GRP_CD varchar2(10 char) NOT NULL,
	GRP_NM varchar2(50 char),
	PRIMARY KEY (GRP_CD)
);


CREATE TABLE CODING_BOARD
(
	NO number NOT NULL,
	SEQ number NOT NULL,
	KIND varchar2(200 char) NOT NULL,
	-- 공지/글
	NOTICE_YN varchar2(1) NOT NULL,
	TITLE varchar2(200 char) NOT NULL,
	REG_DATE date NOT NULL,
	UPD_DATE date NOT NULL,
	CODING_CONTENTS clob NOT NULL,
	READ_CNT number NOT NULL,
	GROUP_KEY varchar2(200 char) NOT NULL UNIQUE,
	id varchar2(200 char) NOT NULL,
	PRIMARY KEY (NO)
);


CREATE TABLE CODING_COMMENT
(
	NO number NOT NULL,
	SEQ number NOT NULL,
	REG_DATE date,
	UPD_DATE date,
	id varchar2(200 char) NOT NULL,
	PRIMARY KEY (NO, SEQ)
);


CREATE TABLE CODING_FILE_GRP
(
	-- 파일 그굽키
	GROUP_KEY varchar2(200 char) NOT NULL,
	-- 업로드된 파일순번
	FILE_SEQ number NOT NULL,
	-- 실제파일 이름
	FILE_REALNAME varchar2(200 char) NOT NULL,
	-- 파일이름
	FILE_NAME varchar2(200 char) NOT NULL,
	-- 파일의 가상 저장경로
	FILE_PATH varchar2(200 char) NOT NULL,
	-- 파일용량
	FILE_LENGTH number NOT NULL,
	-- 파일타입
	FILE_TYPE varchar2(200 char) NOT NULL,
	-- 파일삭제여부
	DEL_YN varchar2(1 char) NOT NULL,
	-- 파일등록일자
	REG_DATE date NOT NULL,
	-- 수정일자
	CHG_DATE date,
	PRIMARY KEY (GROUP_KEY, FILE_SEQ)
);


CREATE TABLE CODING_LIKE
(
	NO number NOT NULL,
	REG_DATE date,
	id varchar2(200 char) NOT NULL,
	PRIMARY KEY (NO, id)
);


CREATE TABLE CODING_LOGIN_HIST
(
	id varchar2(200 char) NOT NULL,
	LOGIN_DATE date NOT NULL,
	IP varchar2(200 char) NOT NULL,
	MAC_ADDR varchar2(200 char) NOT NULL,
	PRIMARY KEY (id, LOGIN_DATE)
);


CREATE TABLE CODING_MEMBERS
(
	id varchar2(200 char) NOT NULL,
	-- 이메일
	EMAIL varchar2(200 char) NOT NULL UNIQUE,
	-- 닉네임
	NICK_NAME varchar2(50 char),
	PASSWORD varchar2(200 char) NOT NULL,
	REG_DATE date,
	DEL_YN varchar2(1 char) NOT NULL,
	GRP_CD varchar2(10 char) NOT NULL,
	PRIMARY KEY (id)
);


CREATE TABLE CODING_MENU
(
	MENU_ID varchar2(200 char) NOT NULL,
	MENU_NM varchar2(200 char) NOT NULL,
	UP_MENU_ID varchar2(200 char) NOT NULL,
	PATH varchar2(200 char) NOT NULL,
	USE_YN varchar2(1 char) NOT NULL,
	REG_ID varchar2(200 char),
	REG_DATE date,
	UPD_ID varchar2(200 char),
	UPD_DATE date,
	PRIMARY KEY (MENU_ID)
);


CREATE TABLE CODING_PW_HIST
(
	id varchar2(200 char) NOT NULL,
	PASSWORD varchar2(200 char),
	CHG_DATE date,
	PRIMARY KEY (id)
);


CREATE TABLE CODING_READCNT_HIST
(
	NO number NOT NULL,
	id varchar2(200 char) NOT NULL,
	READ_DATE date,
	PRIMARY KEY (NO, id)
);



/* Create Foreign Keys */

ALTER TABLE AUTH_MAPPING
	ADD FOREIGN KEY (GRP_CD)
	REFERENCES CODING_AUTH_GRP (GRP_CD)
;


ALTER TABLE CODING_MEMBERS
	ADD FOREIGN KEY (GRP_CD)
	REFERENCES CODING_AUTH_GRP (GRP_CD)
;


ALTER TABLE CODING_COMMENT
	ADD FOREIGN KEY (NO)
	REFERENCES CODING_BOARD (NO)
;


ALTER TABLE CODING_FILE_GRP
	ADD FOREIGN KEY (GROUP_KEY)
	REFERENCES CODING_BOARD (GROUP_KEY)
;


ALTER TABLE CODING_LIKE
	ADD FOREIGN KEY (NO)
	REFERENCES CODING_BOARD (NO)
;


ALTER TABLE CODING_READCNT_HIST
	ADD FOREIGN KEY (NO)
	REFERENCES CODING_BOARD (NO)
;


ALTER TABLE CODING_BOARD
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE CODING_COMMENT
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE CODING_LIKE
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE CODING_LOGIN_HIST
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE CODING_PW_HIST
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE CODING_READCNT_HIST
	ADD FOREIGN KEY (id)
	REFERENCES CODING_MEMBERS (id)
;


ALTER TABLE AUTH_MAPPING
	ADD FOREIGN KEY (MENU_ID)
	REFERENCES CODING_MENU (MENU_ID)
;



/* Comments */

COMMENT ON COLUMN CODING_BOARD.NOTICE_YN IS '공지/글';
COMMENT ON COLUMN CODING_FILE_GRP.GROUP_KEY IS '파일 그굽키';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_SEQ IS '업로드된 파일순번';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_REALNAME IS '실제파일 이름';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_NAME IS '파일이름';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_PATH IS '파일의 가상 저장경로';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_LENGTH IS '파일용량';
COMMENT ON COLUMN CODING_FILE_GRP.FILE_TYPE IS '파일타입';
COMMENT ON COLUMN CODING_FILE_GRP.DEL_YN IS '파일삭제여부';
COMMENT ON COLUMN CODING_FILE_GRP.REG_DATE IS '파일등록일자';
COMMENT ON COLUMN CODING_FILE_GRP.CHG_DATE IS '수정일자';
COMMENT ON COLUMN CODING_MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN CODING_MEMBERS.NICK_NAME IS '닉네임';



